"""empty message

Revision ID: a118faaf13fe
Revises: 
Create Date: 2020-08-01 11:32:44.438835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a118faaf13fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema raven')
    op.create_table('stock',
    sa.Column('dat_create', sa.DateTime(), nullable=False),
    sa.Column('dat_update', sa.DateTime(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('quote_date', sa.String(), nullable=False),
    sa.Column('quote', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id_stock'),
    schema='raven'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock', schema='raven')
    op.execute('drop schema raven')
    # ### end Alembic commands ###
