"""empty message

Revision ID: be0aa0bec051
Revises: 
Create Date: 2020-06-18 13:59:06.833468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be0aa0bec051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema raven')
    op.create_table('stock',
    sa.Column('dat_create', sa.DateTime(), nullable=False),
    sa.Column('dat_update', sa.DateTime(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price_open', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('variation', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('des_date', sa.String(), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id_stock'),
    schema='raven'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('drop schema raven')
    op.drop_table('stock', schema='raven')
    # ### end Alembic commands ###
