default:
    log_config_path: config/logging.yml
    log_level: INFO
    health_path: /health
    db_crypt:
        key: 'Xn2r5u8x/A?D(G+K'
        algorithm: aes
        encode_algorithm: base64
        convert_to: SQL_ASCII
    # sqlalchemy_database_uri: postgresql+psycopg2://raven_adm:raven_adm@localhost:5405/db_raven
    sqlalchemy_track_modifications: False
    sqlalchemy_echo: False
    http:
        use_proxy: no
        retries: 3
        retry_codes: [500, 502, 503, 504]
        backoff_factor: 0.2
    sqs:
        test:
            queue_url: https://sqs.us-east-1.amazonaws.com/898139803216/fila
        region: us-east-1
        polling_seconds: 2
        messages_per_polling: 10
        wait_time: 10
        visibility_timeout: 10
    kafka:
        brokers: kafka.qa-aws.url
        limit_topic: single-risk.offer.notification
        group_id: raven_group
        reset_policy: earliest
        polling_seconds: 5
        consumer_timeout_seconds: 2
    alphavantage:
        url: https://www.alphavantage.co/query
        token: 3TA2XNEK0GE3NQ8G
        timeout: 2
    telegram:
        url: https://api.telegram.org/bot
        token: 1119179717:AAHbh_7Y6vaCo2SjAcu7ITYEVaiTthiticY
        timeout: 2