default:
    log_config_path: config/logging.yml
    log_level: INFO
    health_path: /health
    db_crypt:
        key: 'Xn2r5u8x/A?D(G+K'
        algorithm: aes
        encode_algorithm: base64
        convert_to: SQL_ASCII
    # sqlalchemy_database_uri: postgresql+psycopg2://raven_adm:raven_adm@localhost:5405/db_raven
    sqlalchemy_track_modifications: False
    sqlalchemy_echo: False
    http:
        use_proxy: no
        retries: 3
        retry_codes: [500, 502, 503, 504]
        backoff_factor: 0.2
    alphavantage:
        url: https://www.alphavantage.co/query
        token: 3TA2XNEK0GE3NQ8G
        timeout: 2
    telegram:
        url: https://api.telegram.org/bot
        token: 1119179717:AAHbh_7Y6vaCo2SjAcu7ITYEVaiTthiticY
        timeout: 2
    yahoo:
        url: https://query1.finance.yahoo.com/
        timeout: 2
    heroku:
        url: http://ravensp.herokuapp.com/
        timeout: 2
    count:
        url: https://api.countapi.xyz/
        timeout: 2
    
